# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
    pull_request:
        branches: ['main']

jobs:
    lint:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node 20
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Check lint
              run: eslint \"{src,test}/**/*.ts\"

    build:
        name: build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Check build
              run: ./scripts/build

            - name: Push dist folder
              if: success()
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add dist
                  git commit -m "build: PR #${{ github.event.pull_request.number }}"
                  git push origin main
